[package]
name = "anna-eval"
version = "0.0.0"
authors = ["Anonymous"]

[dependencies]
env_logger                = "0.4"
log                       = "0.3"
rand                      = "0.5"
anna-model             = { path = "../model" }
anna-utils             = { path = "../utils" }
