[package]
name    = "nnet"
version = "0.1.0"
authors = ["Anonymous"]
edition = "2018"

[dependencies]
quickcheck    = "0.7"

rand          = "0.5"
serde         = "1.0"
serde_derive  = "1.0"
tensorflow = { version = "0.14.0" } #, features = ["tensorflow_gpu"] }
