[package]
name = "anna-model"
version = "0.0.0"
authors = ["Anonymous"]

[dependencies]
# byteorder         = "1.0"
# chrono            = "0.3"
# enum_primitive    = "0.1"
# num               = "0.1"
serde             = "1.0"
serde_derive      = "1.0"
