indent_style = "Visual"
tab_spaces = 2

use_small_heuristics = "Max"
fn_args_density = "Compressed"
fn_single_line = true
format_strings = true
merge_imports = true
use_try_shorthand = true

wrap_comments = true
normalize_doc_attributes = true

error_on_line_overflow = true
error_on_unformatted = true
